### PR TITLE
allow carrier id to be passed in

### PR DESCRIPTION
**Pull request by georgeismike**
this will allow a consuming system to know if carrier_id is a valid parameter.

### CODE REVIEW

**Comment by pedromartinez** [comment]
👍

**Comment by captainbeardo** [comment]
Is this actually common to all actions?

**Comment by georgeismike** [comment]
@captainbeardo no. Its used on only 3 of them.

**Comment by captainbeardo** [comment]
Should probably just put it on those 3 then.

**Comment by pedromartinez** [comment]
@captainbeardo The reason is because we need to store it in the Carrier record, and we use the high level credentials as a `permitted_params` type of deal to know what to collect that crosses actions...

If you can think of a better way, I'm all ears. It seemed like the same solution was used for Reactor.

**Comment by captainbeardo** [comment]
I don't understand that comment.

**Comment by captainbeardo** [comment]
👍

**Pull request merged**
