### PR TITLE
update mock example for bigger data balance

### PR DESCRIPTION
**Pull request by georgeismike**
Downstream systems use the mock status in conduit atom.  20.0 bytes is arbitrary and low. I am increase this number so its arbitrary and higher.

### CODE REVIEW

**Comment by pedromartinez** [comment]
I think this PR is fine. Having more representative data is okay with me.

I think @mgates might be talking about something specific to a PR?

**Comment by mgates** [comment]
I mean, this is fine, natch, but I think it's not necessary to do the tests in https://github.com/Hello-Labs/connect-global-ivr/pull/25

**Comment by pedromartinez** [comment]
I guess I'm the dissenting voice here. For integration tests in the IVR project, I'd prefer to mock out using conduit-atom or vcr, not by mocking methods.

Generally speaking, I should be able to internally refactor everything (method names and all) and not impact a single integration test.

**Comment by pedromartinez** [comment]
@coreypurcell @mgates ^

**Comment by coreypurcell** [comment]
I agree with using the mocks provided by the gem, so I don't dissent. I'm referring to testing specific cases that the gem may not provide. In that case it might be safer to not rely on the gem and instead inject your own. If nothing else is using this mock from conduit-atom I don't have a problem changing it here.

**Comment by mgates** [comment]
Sure, I just don't think we need to use an integration test there.

**Pull request merged**
